<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1

| Term |  Brief description |
| :--: | :--: |
| Subsetting | Subsetting means selecting part of a list/array, by either indexing or slicing |
| Indexing | Indexing means extracting the elements (individually) of a list using their corresponding index in the list/array |
| Slicing | Slicing means extracting multiple elements from a list - like from a starting index to the final index |
| Masking | Masking is conditional selecting; it will only output the elements that fit the condition, kind of like an if statement |

In [35]:
# Exercise 2

import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

array_index_0s = np_array_2d[:, 0]
array_index_0s_int = array_index_0s.astype(int)

arrayremainders = array_index_0s_int % 2

print(arrayremainders)

masked = arrayremainders != 0

print(masked)

corr2nd = np_array_2d[masked, 1]

print(corr2nd)


[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']


In [39]:
# Exercise 3

array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])


newarray = array.copy()

newarray[newarray < 50] = -1
newarray[newarray > 50] = 1
newarray[newarray == 50] = 0

print(newarray)





[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
